# FROM postgres

# ARG POSTGRES_DB
# ARG POSTGRES_USER
# ARG POSTGRES_PASSWORD

# ENV POSTGRES_DB=${POSTGRES_DB}
# ENV POSTGRES_USER=${POSTGRES_USER}
# ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Copy the seed file to the initialization directory
# COPY seed.sql /docker-entrypoint-initdb.d/

# Expose the default PostgreSQL port
# EXPOSE 5432